### ISSUE TITLE
Could we return a toJSON with a special type?

### ISSUE THREAD

**Issue by josh-biddick** [ricado-group/js-api-client#28]
Each model class in the API current;y has a `toJSON` method that returns the following type:

```ts
toJSON(): {
    [x: string]: any;
};
``` 
Is there any chance the API could return a more helpful type that describes all of the keys that this method returns? This would save us from re-defining the output to a more defined type, such as:

```ts
type RTUModelJSON = {
    -readonly [P in keyof Models.RTUModel]: Models.RTUModel[P];
}
```  
Having the return type be more explicit would prevent us from having to write wierd types as that above. I know I've probably mentioned this in the past and I know that it may be difficult as the return type isn't a clear map from the members of the class. 

Is it even possible? 

Feel free to reject this proposal if you feel you've already answered it previously :)

**Comment by ashneilson** [comment]
@josh-biddick I hope you're okay with this issue being closed.

Utilizing the Models without converting `toJSON` will simplify your code-base and bring a slight performance improvement 🙂
