### ISSUE TITLE
toJSON() missing properties

### ISSUE THREAD

**Issue by michaelpeterlee** [ricado-group/js-api-client#46]
OVERVIEW:

Image depicts actual Class instance and toJSON() result with missing properties, below.
![image](https://user-images.githubusercontent.com/19398181/126241153-80b00ba3-1daa-4554-bc08-601d59d33fb7.png)

PROBLEM:
```
const packruns = Controllers.Packhouse.Site.PackrunController.getAll(siteId, options);
return packruns.map((packrun) => packrun.toJSON() as IPackrunModel);
```

WORKAROUND:
```
import { ModelSerializer } from "@ricado/core-ui";
return packruns.map((packrun) => ModelSerializer.toJSON(packrun) as IPackrunModel);
```

BACKGROUND:

Class instance serialisation provides a simple way to extend for view models. We cannot use Object assign/spread as they lose important properties, so we must either explicitly map property names [opinionated and laborious when props change], or use a serialisation utility.

Eg.
```
// Optimal
const _packrun = ModelSerializer.toJSON(packrun); 
return {
   ..._packrun,
   myNewProp: 'hi'
};
```

```
// Opinionated and requires rework should base model props change
return {
   id : _packrun.id,
   name : _packrun.name,
   ...
   myNewProp: 'hi'
};
```

**Comment by ashneilson** [comment]
Hey @michaelpeterlee!

Which properties are getting missed? Provided you are using the latest API Client version (would be good to double check which version you are on) - the ```toJSON()``` function builds the simple object with all properties as expected.

It would be good to briefly discuss this one with @josh-biddick as ideally I would like to remove the ```toJSON()``` method as it causes confusion and get's used too often which causes a large performance impact.

Are you not able to store and use the Model Class as provided? If you only need a few properties from it, then wouldn't you just grab those few properties anyhow rather than using the spread ```...``` operator - otherwise you're storing other properties you don't need?

**Comment by josh-biddick** [comment]
I can confirm that the `siteId` property is missing when transformed using `.toJSON()`. @michaelpeterlee Maybe you could do something similar to this (https://github.com/ricado-group/gen4-servicetech-web/blob/master/src/Devices/deviceManager.ts#L55). If not using the spread operator really does become an issue, it might be worth discussing further at a later date?

**Comment by michaelpeterlee** [comment]
@ashneilson @josh-biddick I've adopted Object.create() to conclude this iteration:

```
const myNewInstance = Object.create(packrun); 
myNewInstance.myNewProp = 'hi';
return myNewInstance;
```

Please find further consideration, below.

Encapsulation:

Without conducting any Javascript performance tests, in Java we suffered dearly from Object instantiation at scale so we cached lookup data and services as singletons and gained a massive performance improvement. 

I appreciate Classes where we have private data or provide services like event emitters and display formats, for example.
If we are just referencing data, then we will likely achieve more performance without classes.

Classes are a good consideration; it can be handy to refer class member method to format/express data, Eg.

```
// MomentJS is provided by the "flyweight" pattern [reusable properties and methods exist on a single delegate object courtesy of the javascript prototype]

packruns[packrunId].unix('updatedTimestamp');
packruns[packrunId].format('updatedTimestamp','YY-MM-DD');
```

**Comment by ashneilson** [comment]
Agreed on a plan to:

- Remove the ```.toJSON()``` method
- Remove getters and utilize public properties (might be readonly if Babel transpiles them okay)
- Potentially make the ```.fromJSON(data)``` method internal to the API Client Library

**Comment by michaelpeterlee** [comment]
Ash has explained why `siteId` is missing, we also cast a critical eye on JS Classes versus POJO plain-old-javascript-objects. We decided to keep classes whilst removing getter from the prototype, simply because they will never be used [more verbose]. We have not reviewed Class instantiation overhead for this iteration. 

To conclude, we have settled on the following implementations, with #1 incurring the least RAM overhead:

1. Object.create()
1.1. Keep all existing properties, so you can add more with minimal RAM overhead due to prototype inheritance

2. Compose new POJO
2.1. Compose only the properties you need

@ashneilson I'm satisfied with this as an iteration to close this issue.

**Comment by ashneilson** [comment]
@josh-biddick and @michaelpeterlee this task has finally been completed! A new version of the API Client v2 has been released which has the "breaking changes":

- Remove the `siteId` property
- Remove the `toJSON()` method
- Expose all of the class properties as public without the use of getters and setters

https://github.com/ricado-group/js-api-client/releases/tag/2.0.0
