### ISSUE TITLE
UserAccountActionTokenController > create requires issueTimestamp and expireTimestamp 

### ISSUE THREAD

**Issue by josh-biddick** [ricado-group/js-api-client#66]
When creating a new UserActionToken via the `Controllers.UserAccountActionTokenController.create` method. The required arguments include a `issueTimestamp` and `expireTimestamp`. 

```ts
export type CreateData = {
  /**
  * The Account this Action Token belongs to
  */
  accountId: string;
  /**
  * The Company this Action Token belongs to
  */
  companyId: string;
  /**
  * The Action that can be Performed using this Action Token
  */
  action: string;
  /**
  * When the Action Token was issued
  */
  issueTimestamp: Date;
  /**
  * When the Action Token will expire
  */
  expireTimestamp: Date;
  /**
  * When the last API call using this Action Token was made
  */
  activityTimestamp?: Date;
  /**
  * When the Action was Completed
  */
  completedTimestamp?: Date;
  /**
  * When the Action Email was Sent
  */
  emailTimestamp?: Date;
};
```  

Previously, I believe these were optional or perhaps handled by the API itself. 

Should these be something that's handled at the App level and if so, what would the default `expireTimestamp` value need to be?

**Comment by ashneilson** [comment]
@josh-biddick Thanks for raising this issue.

I would avoid using the ```.create()``` method as this requires you to specify all of these parameters and won't handle things like emailing the user with a link for the Action.

Instead use the ```.createToken()``` method which takes an Email, Action and Provider ID: https://ricado-group.github.io/js-api-client/Controllers.UserAccountActionTokenController.html
