### ISSUE TITLE
[Enhancement] - Export namespaced interfaces with global names

### ISSUE THREAD

**Issue by josh-biddick** [ricado-group/js-api-client#7]
Cheers for the awesome work with the recent changes to the API Client. 

One thing I'd like to suggest would be to export Interfaces/Types that are nested within namespaces to be accessible globally. 

An example is as follows:

```ts
import { Controllers } from "@ricado/api-client";

const readpointUpdateHandler = (
  siteId: string,
  pointValues: Controllers.Site.PointController.PointValueItem[]
) => {
  // do stuff
};
```
Currently, we can only reference the PointValueItem Interface via the namespace `Controllers.Site.PointController`. I imagine that in future these namespaces could become quite cumbersome should we need to type these out every time.

Would you consider having more specific names for Interfaces and exposing them globally so that we could do the following?

```ts
import { PointValueItem } from "@ricado/api-client";
```

**Comment by ashneilson** [comment]
@josh-biddick While I completely understand your thoughts on making this easier, we would simply be trading the ```Controllers.Site.PointController.PointValueItem``` namespace for something like ```SitePointControllerPointValueItem``` which feels a lot more verbose to me.

It should be possible to import / redeclare the PointValueItem type in a simpler way - I'm just unsure on the correct way to do this at present.

An example of how this could clash into the future is the concept of a ```VarietyCode``` in RICADO Pack and RICADO AgriHort:

```Controllers.Packhouse.Site.VarietyController.VarietyCode```

and

```Controllers.AgriHort.Site.VarietyController.VarietyCode```
