### ISSUE TITLE
Shift > getOne() > HTTP 404

### ISSUE THREAD

**Issue by michaelpeterlee** [ricado-group/js-api-client#71]
![image](https://user-images.githubusercontent.com/19398181/130562506-ba25dbad-94ce-4569-bc65-52dc88310542.png)

API reference: https://ricado-group.github.io/js-api-client/Controllers.Packhouse.Site.ShiftController.html#.getOne

Calling code: `Controllers.Packhouse.Site.ShiftHourlyEntryController.getOne(siteId, shiftId)`

Results in the following request: https://api.ricado.co.nz/api/4.0/packhouse/sites/7/shift-hourly-entries/6a98ef50-55ce-4689-8c6e-8fbe125a9f2d 

https://packhouse.ricado.co.nz requests as follows: https://api-staging.ricado.co.nz/api/4.0/packhouse/sites/7/shift-hourly-entries?shiftId=6a98ef50-55ce-4689-8c6e-8fbe125a9f2d

**Comment by ashneilson** [comment]
@michaelpeterlee Are you able to confirm that you are using the ```hourlyEntryId``` and not the ```shiftId``` in the ```.getOne()``` method?

@tainoNZ Any insight / thoughts from you on this potential issue?

**Comment by tainoNZ** [comment]
@ashneilson @michaelpeterlee yeah I've just run it in Postman and the shiftId is getting used. As its 'ShiftHourlyEntryController' and you are trying to 'getOne' its the Shift Hourly Entry ID you need to use not the Shift ID. You've also linked the wrong API Reference 😉 
Here is the correct one. https://ricado-group.github.io/js-api-client/Controllers.Packhouse.Site.ShiftHourlyEntryController.html#.getOne

**Comment by michaelpeterlee** [comment]
Thanks folks progressing on that now.

**Comment by michaelpeterlee** [comment]
I should have referred getAll(), thanks for the support folks.
